// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: foliv.proto

package foliv;

public final class FolivOuterClass {
  private FolivOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code foliv.Command}
   */
  public enum Command
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Empty = 0;</code>
     */
    Empty(0),
    /**
     * <code>Connect = 1;</code>
     */
    Connect(1),
    /**
     * <code>Associate = 3;</code>
     */
    Associate(3),
    /**
     * <code>Mux = 127;</code>
     */
    Mux(127),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Empty = 0;</code>
     */
    public static final int Empty_VALUE = 0;
    /**
     * <code>Connect = 1;</code>
     */
    public static final int Connect_VALUE = 1;
    /**
     * <code>Associate = 3;</code>
     */
    public static final int Associate_VALUE = 3;
    /**
     * <code>Mux = 127;</code>
     */
    public static final int Mux_VALUE = 127;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Command valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Command forNumber(int value) {
      switch (value) {
        case 0: return Empty;
        case 1: return Connect;
        case 3: return Associate;
        case 127: return Mux;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Command>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Command> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Command>() {
            public Command findValueByNumber(int number) {
              return Command.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return foliv.FolivOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final Command[] VALUES = values();

    public static Command valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Command(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:foliv.Command)
  }

  /**
   * Protobuf enum {@code foliv.AddressType}
   */
  public enum AddressType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>InvalidType = 0;</code>
     */
    InvalidType(0),
    /**
     * <code>IPv4 = 1;</code>
     */
    IPv4(1),
    /**
     * <code>DomainName = 3;</code>
     */
    DomainName(3),
    /**
     * <code>IPv6 = 4;</code>
     */
    IPv6(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>InvalidType = 0;</code>
     */
    public static final int InvalidType_VALUE = 0;
    /**
     * <code>IPv4 = 1;</code>
     */
    public static final int IPv4_VALUE = 1;
    /**
     * <code>DomainName = 3;</code>
     */
    public static final int DomainName_VALUE = 3;
    /**
     * <code>IPv6 = 4;</code>
     */
    public static final int IPv6_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AddressType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static AddressType forNumber(int value) {
      switch (value) {
        case 0: return InvalidType;
        case 1: return IPv4;
        case 3: return DomainName;
        case 4: return IPv6;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AddressType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AddressType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AddressType>() {
            public AddressType findValueByNumber(int number) {
              return AddressType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return foliv.FolivOuterClass.getDescriptor().getEnumTypes().get(1);
    }

    private static final AddressType[] VALUES = values();

    public static AddressType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AddressType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:foliv.AddressType)
  }

  public interface FolivOrBuilder extends
      // @@protoc_insertion_point(interface_extends:foliv.Foliv)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string userHash = 1;</code>
     * @return The userHash.
     */
    java.lang.String getUserHash();
    /**
     * <code>string userHash = 1;</code>
     * @return The bytes for userHash.
     */
    com.google.protobuf.ByteString
        getUserHashBytes();

    /**
     * <code>.foliv.Command command = 2;</code>
     * @return The enum numeric value on the wire for command.
     */
    int getCommandValue();
    /**
     * <code>.foliv.Command command = 2;</code>
     * @return The command.
     */
    foliv.FolivOuterClass.Command getCommand();

    /**
     * <code>.foliv.AddressType addressType = 3;</code>
     * @return The enum numeric value on the wire for addressType.
     */
    int getAddressTypeValue();
    /**
     * <code>.foliv.AddressType addressType = 3;</code>
     * @return The addressType.
     */
    foliv.FolivOuterClass.AddressType getAddressType();

    /**
     * <code>bytes address = 4;</code>
     * @return The address.
     */
    com.google.protobuf.ByteString getAddress();

    /**
     * <code>uint32 port = 5;</code>
     * @return The port.
     */
    int getPort();

    /**
     * <code>string sourceName = 6;</code>
     * @return The sourceName.
     */
    java.lang.String getSourceName();
    /**
     * <code>string sourceName = 6;</code>
     * @return The bytes for sourceName.
     */
    com.google.protobuf.ByteString
        getSourceNameBytes();

    /**
     * <code>string routerName = 7;</code>
     * @return The routerName.
     */
    java.lang.String getRouterName();
    /**
     * <code>string routerName = 7;</code>
     * @return The bytes for routerName.
     */
    com.google.protobuf.ByteString
        getRouterNameBytes();

    /**
     * <code>string processName = 8;</code>
     * @return The processName.
     */
    java.lang.String getProcessName();
    /**
     * <code>string processName = 8;</code>
     * @return The bytes for processName.
     */
    com.google.protobuf.ByteString
        getProcessNameBytes();

    /**
     * <code>repeated bytes xForwardedFor = 9;</code>
     * @return A list containing the xForwardedFor.
     */
    java.util.List<com.google.protobuf.ByteString> getXForwardedForList();
    /**
     * <code>repeated bytes xForwardedFor = 9;</code>
     * @return The count of xForwardedFor.
     */
    int getXForwardedForCount();
    /**
     * <code>repeated bytes xForwardedFor = 9;</code>
     * @param index The index of the element to return.
     * @return The xForwardedFor at the given index.
     */
    com.google.protobuf.ByteString getXForwardedFor(int index);

    /**
     * <code>bool isTouch = 10;</code>
     * @return The isTouch.
     */
    boolean getIsTouch();

    /**
     * <code>uint32 muxID = 11;</code>
     * @return The muxID.
     */
    int getMuxID();

    /**
     * <code>string platform = 12;</code>
     * @return The platform.
     */
    java.lang.String getPlatform();
    /**
     * <code>string platform = 12;</code>
     * @return The bytes for platform.
     */
    com.google.protobuf.ByteString
        getPlatformBytes();

    /**
     * <code>bytes requestID = 13;</code>
     * @return The requestID.
     */
    com.google.protobuf.ByteString getRequestID();

    /**
     * <code>uint32 routerLevel = 14;</code>
     * @return The routerLevel.
     */
    int getRouterLevel();

    /**
     * <code>string userAgent = 15;</code>
     * @return The userAgent.
     */
    java.lang.String getUserAgent();
    /**
     * <code>string userAgent = 15;</code>
     * @return The bytes for userAgent.
     */
    com.google.protobuf.ByteString
        getUserAgentBytes();

    /**
     * <code>uint32 requestHop = 16;</code>
     * @return The requestHop.
     */
    int getRequestHop();

    /**
     * <code>uint32 appID = 17;</code>
     * @return The appID.
     */
    int getAppID();

    /**
     * <code>uint32 peerID = 18;</code>
     * @return The peerID.
     */
    int getPeerID();

    /**
     * <code>uint32 version = 19;</code>
     * @return The version.
     */
    int getVersion();

    /**
     * <code>uint32 roundtripTime = 20;</code>
     * @return The roundtripTime.
     */
    int getRoundtripTime();
  }
  /**
   * Protobuf type {@code foliv.Foliv}
   */
  public static final class Foliv extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:foliv.Foliv)
      FolivOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Foliv.newBuilder() to construct.
    private Foliv(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Foliv() {
      userHash_ = "";
      command_ = 0;
      addressType_ = 0;
      address_ = com.google.protobuf.ByteString.EMPTY;
      sourceName_ = "";
      routerName_ = "";
      processName_ = "";
      xForwardedFor_ = java.util.Collections.emptyList();
      platform_ = "";
      requestID_ = com.google.protobuf.ByteString.EMPTY;
      userAgent_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Foliv();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Foliv(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userHash_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              command_ = rawValue;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              addressType_ = rawValue;
              break;
            }
            case 34: {

              address_ = input.readBytes();
              break;
            }
            case 40: {

              port_ = input.readUInt32();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              sourceName_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              routerName_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              processName_ = s;
              break;
            }
            case 74: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                xForwardedFor_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              xForwardedFor_.add(input.readBytes());
              break;
            }
            case 80: {

              isTouch_ = input.readBool();
              break;
            }
            case 88: {

              muxID_ = input.readUInt32();
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();

              platform_ = s;
              break;
            }
            case 106: {

              requestID_ = input.readBytes();
              break;
            }
            case 112: {

              routerLevel_ = input.readUInt32();
              break;
            }
            case 122: {
              java.lang.String s = input.readStringRequireUtf8();

              userAgent_ = s;
              break;
            }
            case 128: {

              requestHop_ = input.readUInt32();
              break;
            }
            case 136: {

              appID_ = input.readUInt32();
              break;
            }
            case 144: {

              peerID_ = input.readUInt32();
              break;
            }
            case 152: {

              version_ = input.readUInt32();
              break;
            }
            case 160: {

              roundtripTime_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          xForwardedFor_ = java.util.Collections.unmodifiableList(xForwardedFor_); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return foliv.FolivOuterClass.internal_static_foliv_Foliv_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return foliv.FolivOuterClass.internal_static_foliv_Foliv_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              foliv.FolivOuterClass.Foliv.class, foliv.FolivOuterClass.Foliv.Builder.class);
    }

    public static final int USERHASH_FIELD_NUMBER = 1;
    private volatile java.lang.Object userHash_;
    /**
     * <code>string userHash = 1;</code>
     * @return The userHash.
     */
    @java.lang.Override
    public java.lang.String getUserHash() {
      java.lang.Object ref = userHash_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userHash_ = s;
        return s;
      }
    }
    /**
     * <code>string userHash = 1;</code>
     * @return The bytes for userHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserHashBytes() {
      java.lang.Object ref = userHash_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMMAND_FIELD_NUMBER = 2;
    private int command_;
    /**
     * <code>.foliv.Command command = 2;</code>
     * @return The enum numeric value on the wire for command.
     */
    @java.lang.Override public int getCommandValue() {
      return command_;
    }
    /**
     * <code>.foliv.Command command = 2;</code>
     * @return The command.
     */
    @java.lang.Override public foliv.FolivOuterClass.Command getCommand() {
      @SuppressWarnings("deprecation")
      foliv.FolivOuterClass.Command result = foliv.FolivOuterClass.Command.valueOf(command_);
      return result == null ? foliv.FolivOuterClass.Command.UNRECOGNIZED : result;
    }

    public static final int ADDRESSTYPE_FIELD_NUMBER = 3;
    private int addressType_;
    /**
     * <code>.foliv.AddressType addressType = 3;</code>
     * @return The enum numeric value on the wire for addressType.
     */
    @java.lang.Override public int getAddressTypeValue() {
      return addressType_;
    }
    /**
     * <code>.foliv.AddressType addressType = 3;</code>
     * @return The addressType.
     */
    @java.lang.Override public foliv.FolivOuterClass.AddressType getAddressType() {
      @SuppressWarnings("deprecation")
      foliv.FolivOuterClass.AddressType result = foliv.FolivOuterClass.AddressType.valueOf(addressType_);
      return result == null ? foliv.FolivOuterClass.AddressType.UNRECOGNIZED : result;
    }

    public static final int ADDRESS_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString address_;
    /**
     * <code>bytes address = 4;</code>
     * @return The address.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAddress() {
      return address_;
    }

    public static final int PORT_FIELD_NUMBER = 5;
    private int port_;
    /**
     * <code>uint32 port = 5;</code>
     * @return The port.
     */
    @java.lang.Override
    public int getPort() {
      return port_;
    }

    public static final int SOURCENAME_FIELD_NUMBER = 6;
    private volatile java.lang.Object sourceName_;
    /**
     * <code>string sourceName = 6;</code>
     * @return The sourceName.
     */
    @java.lang.Override
    public java.lang.String getSourceName() {
      java.lang.Object ref = sourceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceName_ = s;
        return s;
      }
    }
    /**
     * <code>string sourceName = 6;</code>
     * @return The bytes for sourceName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSourceNameBytes() {
      java.lang.Object ref = sourceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROUTERNAME_FIELD_NUMBER = 7;
    private volatile java.lang.Object routerName_;
    /**
     * <code>string routerName = 7;</code>
     * @return The routerName.
     */
    @java.lang.Override
    public java.lang.String getRouterName() {
      java.lang.Object ref = routerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        routerName_ = s;
        return s;
      }
    }
    /**
     * <code>string routerName = 7;</code>
     * @return The bytes for routerName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRouterNameBytes() {
      java.lang.Object ref = routerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        routerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROCESSNAME_FIELD_NUMBER = 8;
    private volatile java.lang.Object processName_;
    /**
     * <code>string processName = 8;</code>
     * @return The processName.
     */
    @java.lang.Override
    public java.lang.String getProcessName() {
      java.lang.Object ref = processName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        processName_ = s;
        return s;
      }
    }
    /**
     * <code>string processName = 8;</code>
     * @return The bytes for processName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProcessNameBytes() {
      java.lang.Object ref = processName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        processName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int XFORWARDEDFOR_FIELD_NUMBER = 9;
    private java.util.List<com.google.protobuf.ByteString> xForwardedFor_;
    /**
     * <code>repeated bytes xForwardedFor = 9;</code>
     * @return A list containing the xForwardedFor.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getXForwardedForList() {
      return xForwardedFor_;
    }
    /**
     * <code>repeated bytes xForwardedFor = 9;</code>
     * @return The count of xForwardedFor.
     */
    public int getXForwardedForCount() {
      return xForwardedFor_.size();
    }
    /**
     * <code>repeated bytes xForwardedFor = 9;</code>
     * @param index The index of the element to return.
     * @return The xForwardedFor at the given index.
     */
    public com.google.protobuf.ByteString getXForwardedFor(int index) {
      return xForwardedFor_.get(index);
    }

    public static final int ISTOUCH_FIELD_NUMBER = 10;
    private boolean isTouch_;
    /**
     * <code>bool isTouch = 10;</code>
     * @return The isTouch.
     */
    @java.lang.Override
    public boolean getIsTouch() {
      return isTouch_;
    }

    public static final int MUXID_FIELD_NUMBER = 11;
    private int muxID_;
    /**
     * <code>uint32 muxID = 11;</code>
     * @return The muxID.
     */
    @java.lang.Override
    public int getMuxID() {
      return muxID_;
    }

    public static final int PLATFORM_FIELD_NUMBER = 12;
    private volatile java.lang.Object platform_;
    /**
     * <code>string platform = 12;</code>
     * @return The platform.
     */
    @java.lang.Override
    public java.lang.String getPlatform() {
      java.lang.Object ref = platform_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        platform_ = s;
        return s;
      }
    }
    /**
     * <code>string platform = 12;</code>
     * @return The bytes for platform.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPlatformBytes() {
      java.lang.Object ref = platform_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        platform_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUESTID_FIELD_NUMBER = 13;
    private com.google.protobuf.ByteString requestID_;
    /**
     * <code>bytes requestID = 13;</code>
     * @return The requestID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRequestID() {
      return requestID_;
    }

    public static final int ROUTERLEVEL_FIELD_NUMBER = 14;
    private int routerLevel_;
    /**
     * <code>uint32 routerLevel = 14;</code>
     * @return The routerLevel.
     */
    @java.lang.Override
    public int getRouterLevel() {
      return routerLevel_;
    }

    public static final int USERAGENT_FIELD_NUMBER = 15;
    private volatile java.lang.Object userAgent_;
    /**
     * <code>string userAgent = 15;</code>
     * @return The userAgent.
     */
    @java.lang.Override
    public java.lang.String getUserAgent() {
      java.lang.Object ref = userAgent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userAgent_ = s;
        return s;
      }
    }
    /**
     * <code>string userAgent = 15;</code>
     * @return The bytes for userAgent.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserAgentBytes() {
      java.lang.Object ref = userAgent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userAgent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUESTHOP_FIELD_NUMBER = 16;
    private int requestHop_;
    /**
     * <code>uint32 requestHop = 16;</code>
     * @return The requestHop.
     */
    @java.lang.Override
    public int getRequestHop() {
      return requestHop_;
    }

    public static final int APPID_FIELD_NUMBER = 17;
    private int appID_;
    /**
     * <code>uint32 appID = 17;</code>
     * @return The appID.
     */
    @java.lang.Override
    public int getAppID() {
      return appID_;
    }

    public static final int PEERID_FIELD_NUMBER = 18;
    private int peerID_;
    /**
     * <code>uint32 peerID = 18;</code>
     * @return The peerID.
     */
    @java.lang.Override
    public int getPeerID() {
      return peerID_;
    }

    public static final int VERSION_FIELD_NUMBER = 19;
    private int version_;
    /**
     * <code>uint32 version = 19;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }

    public static final int ROUNDTRIPTIME_FIELD_NUMBER = 20;
    private int roundtripTime_;
    /**
     * <code>uint32 roundtripTime = 20;</code>
     * @return The roundtripTime.
     */
    @java.lang.Override
    public int getRoundtripTime() {
      return roundtripTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserHashBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userHash_);
      }
      if (command_ != foliv.FolivOuterClass.Command.Empty.getNumber()) {
        output.writeEnum(2, command_);
      }
      if (addressType_ != foliv.FolivOuterClass.AddressType.InvalidType.getNumber()) {
        output.writeEnum(3, addressType_);
      }
      if (!address_.isEmpty()) {
        output.writeBytes(4, address_);
      }
      if (port_ != 0) {
        output.writeUInt32(5, port_);
      }
      if (!getSourceNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, sourceName_);
      }
      if (!getRouterNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, routerName_);
      }
      if (!getProcessNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, processName_);
      }
      for (int i = 0; i < xForwardedFor_.size(); i++) {
        output.writeBytes(9, xForwardedFor_.get(i));
      }
      if (isTouch_ != false) {
        output.writeBool(10, isTouch_);
      }
      if (muxID_ != 0) {
        output.writeUInt32(11, muxID_);
      }
      if (!getPlatformBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, platform_);
      }
      if (!requestID_.isEmpty()) {
        output.writeBytes(13, requestID_);
      }
      if (routerLevel_ != 0) {
        output.writeUInt32(14, routerLevel_);
      }
      if (!getUserAgentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 15, userAgent_);
      }
      if (requestHop_ != 0) {
        output.writeUInt32(16, requestHop_);
      }
      if (appID_ != 0) {
        output.writeUInt32(17, appID_);
      }
      if (peerID_ != 0) {
        output.writeUInt32(18, peerID_);
      }
      if (version_ != 0) {
        output.writeUInt32(19, version_);
      }
      if (roundtripTime_ != 0) {
        output.writeUInt32(20, roundtripTime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserHashBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userHash_);
      }
      if (command_ != foliv.FolivOuterClass.Command.Empty.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, command_);
      }
      if (addressType_ != foliv.FolivOuterClass.AddressType.InvalidType.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, addressType_);
      }
      if (!address_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, address_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, port_);
      }
      if (!getSourceNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, sourceName_);
      }
      if (!getRouterNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, routerName_);
      }
      if (!getProcessNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, processName_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < xForwardedFor_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(xForwardedFor_.get(i));
        }
        size += dataSize;
        size += 1 * getXForwardedForList().size();
      }
      if (isTouch_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(10, isTouch_);
      }
      if (muxID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(11, muxID_);
      }
      if (!getPlatformBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, platform_);
      }
      if (!requestID_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, requestID_);
      }
      if (routerLevel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(14, routerLevel_);
      }
      if (!getUserAgentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, userAgent_);
      }
      if (requestHop_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(16, requestHop_);
      }
      if (appID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(17, appID_);
      }
      if (peerID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(18, peerID_);
      }
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(19, version_);
      }
      if (roundtripTime_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(20, roundtripTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof foliv.FolivOuterClass.Foliv)) {
        return super.equals(obj);
      }
      foliv.FolivOuterClass.Foliv other = (foliv.FolivOuterClass.Foliv) obj;

      if (!getUserHash()
          .equals(other.getUserHash())) return false;
      if (command_ != other.command_) return false;
      if (addressType_ != other.addressType_) return false;
      if (!getAddress()
          .equals(other.getAddress())) return false;
      if (getPort()
          != other.getPort()) return false;
      if (!getSourceName()
          .equals(other.getSourceName())) return false;
      if (!getRouterName()
          .equals(other.getRouterName())) return false;
      if (!getProcessName()
          .equals(other.getProcessName())) return false;
      if (!getXForwardedForList()
          .equals(other.getXForwardedForList())) return false;
      if (getIsTouch()
          != other.getIsTouch()) return false;
      if (getMuxID()
          != other.getMuxID()) return false;
      if (!getPlatform()
          .equals(other.getPlatform())) return false;
      if (!getRequestID()
          .equals(other.getRequestID())) return false;
      if (getRouterLevel()
          != other.getRouterLevel()) return false;
      if (!getUserAgent()
          .equals(other.getUserAgent())) return false;
      if (getRequestHop()
          != other.getRequestHop()) return false;
      if (getAppID()
          != other.getAppID()) return false;
      if (getPeerID()
          != other.getPeerID()) return false;
      if (getVersion()
          != other.getVersion()) return false;
      if (getRoundtripTime()
          != other.getRoundtripTime()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERHASH_FIELD_NUMBER;
      hash = (53 * hash) + getUserHash().hashCode();
      hash = (37 * hash) + COMMAND_FIELD_NUMBER;
      hash = (53 * hash) + command_;
      hash = (37 * hash) + ADDRESSTYPE_FIELD_NUMBER;
      hash = (53 * hash) + addressType_;
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (37 * hash) + SOURCENAME_FIELD_NUMBER;
      hash = (53 * hash) + getSourceName().hashCode();
      hash = (37 * hash) + ROUTERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getRouterName().hashCode();
      hash = (37 * hash) + PROCESSNAME_FIELD_NUMBER;
      hash = (53 * hash) + getProcessName().hashCode();
      if (getXForwardedForCount() > 0) {
        hash = (37 * hash) + XFORWARDEDFOR_FIELD_NUMBER;
        hash = (53 * hash) + getXForwardedForList().hashCode();
      }
      hash = (37 * hash) + ISTOUCH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsTouch());
      hash = (37 * hash) + MUXID_FIELD_NUMBER;
      hash = (53 * hash) + getMuxID();
      hash = (37 * hash) + PLATFORM_FIELD_NUMBER;
      hash = (53 * hash) + getPlatform().hashCode();
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestID().hashCode();
      hash = (37 * hash) + ROUTERLEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getRouterLevel();
      hash = (37 * hash) + USERAGENT_FIELD_NUMBER;
      hash = (53 * hash) + getUserAgent().hashCode();
      hash = (37 * hash) + REQUESTHOP_FIELD_NUMBER;
      hash = (53 * hash) + getRequestHop();
      hash = (37 * hash) + APPID_FIELD_NUMBER;
      hash = (53 * hash) + getAppID();
      hash = (37 * hash) + PEERID_FIELD_NUMBER;
      hash = (53 * hash) + getPeerID();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + ROUNDTRIPTIME_FIELD_NUMBER;
      hash = (53 * hash) + getRoundtripTime();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static foliv.FolivOuterClass.Foliv parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static foliv.FolivOuterClass.Foliv parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static foliv.FolivOuterClass.Foliv parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static foliv.FolivOuterClass.Foliv parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static foliv.FolivOuterClass.Foliv parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static foliv.FolivOuterClass.Foliv parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static foliv.FolivOuterClass.Foliv parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static foliv.FolivOuterClass.Foliv parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static foliv.FolivOuterClass.Foliv parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static foliv.FolivOuterClass.Foliv parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static foliv.FolivOuterClass.Foliv parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static foliv.FolivOuterClass.Foliv parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(foliv.FolivOuterClass.Foliv prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code foliv.Foliv}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:foliv.Foliv)
        foliv.FolivOuterClass.FolivOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return foliv.FolivOuterClass.internal_static_foliv_Foliv_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return foliv.FolivOuterClass.internal_static_foliv_Foliv_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                foliv.FolivOuterClass.Foliv.class, foliv.FolivOuterClass.Foliv.Builder.class);
      }

      // Construct using foliv.FolivOuterClass.Foliv.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userHash_ = "";

        command_ = 0;

        addressType_ = 0;

        address_ = com.google.protobuf.ByteString.EMPTY;

        port_ = 0;

        sourceName_ = "";

        routerName_ = "";

        processName_ = "";

        xForwardedFor_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        isTouch_ = false;

        muxID_ = 0;

        platform_ = "";

        requestID_ = com.google.protobuf.ByteString.EMPTY;

        routerLevel_ = 0;

        userAgent_ = "";

        requestHop_ = 0;

        appID_ = 0;

        peerID_ = 0;

        version_ = 0;

        roundtripTime_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return foliv.FolivOuterClass.internal_static_foliv_Foliv_descriptor;
      }

      @java.lang.Override
      public foliv.FolivOuterClass.Foliv getDefaultInstanceForType() {
        return foliv.FolivOuterClass.Foliv.getDefaultInstance();
      }

      @java.lang.Override
      public foliv.FolivOuterClass.Foliv build() {
        foliv.FolivOuterClass.Foliv result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public foliv.FolivOuterClass.Foliv buildPartial() {
        foliv.FolivOuterClass.Foliv result = new foliv.FolivOuterClass.Foliv(this);
        int from_bitField0_ = bitField0_;
        result.userHash_ = userHash_;
        result.command_ = command_;
        result.addressType_ = addressType_;
        result.address_ = address_;
        result.port_ = port_;
        result.sourceName_ = sourceName_;
        result.routerName_ = routerName_;
        result.processName_ = processName_;
        if (((bitField0_ & 0x00000001) != 0)) {
          xForwardedFor_ = java.util.Collections.unmodifiableList(xForwardedFor_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.xForwardedFor_ = xForwardedFor_;
        result.isTouch_ = isTouch_;
        result.muxID_ = muxID_;
        result.platform_ = platform_;
        result.requestID_ = requestID_;
        result.routerLevel_ = routerLevel_;
        result.userAgent_ = userAgent_;
        result.requestHop_ = requestHop_;
        result.appID_ = appID_;
        result.peerID_ = peerID_;
        result.version_ = version_;
        result.roundtripTime_ = roundtripTime_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof foliv.FolivOuterClass.Foliv) {
          return mergeFrom((foliv.FolivOuterClass.Foliv)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(foliv.FolivOuterClass.Foliv other) {
        if (other == foliv.FolivOuterClass.Foliv.getDefaultInstance()) return this;
        if (!other.getUserHash().isEmpty()) {
          userHash_ = other.userHash_;
          onChanged();
        }
        if (other.command_ != 0) {
          setCommandValue(other.getCommandValue());
        }
        if (other.addressType_ != 0) {
          setAddressTypeValue(other.getAddressTypeValue());
        }
        if (other.getAddress() != com.google.protobuf.ByteString.EMPTY) {
          setAddress(other.getAddress());
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        if (!other.getSourceName().isEmpty()) {
          sourceName_ = other.sourceName_;
          onChanged();
        }
        if (!other.getRouterName().isEmpty()) {
          routerName_ = other.routerName_;
          onChanged();
        }
        if (!other.getProcessName().isEmpty()) {
          processName_ = other.processName_;
          onChanged();
        }
        if (!other.xForwardedFor_.isEmpty()) {
          if (xForwardedFor_.isEmpty()) {
            xForwardedFor_ = other.xForwardedFor_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureXForwardedForIsMutable();
            xForwardedFor_.addAll(other.xForwardedFor_);
          }
          onChanged();
        }
        if (other.getIsTouch() != false) {
          setIsTouch(other.getIsTouch());
        }
        if (other.getMuxID() != 0) {
          setMuxID(other.getMuxID());
        }
        if (!other.getPlatform().isEmpty()) {
          platform_ = other.platform_;
          onChanged();
        }
        if (other.getRequestID() != com.google.protobuf.ByteString.EMPTY) {
          setRequestID(other.getRequestID());
        }
        if (other.getRouterLevel() != 0) {
          setRouterLevel(other.getRouterLevel());
        }
        if (!other.getUserAgent().isEmpty()) {
          userAgent_ = other.userAgent_;
          onChanged();
        }
        if (other.getRequestHop() != 0) {
          setRequestHop(other.getRequestHop());
        }
        if (other.getAppID() != 0) {
          setAppID(other.getAppID());
        }
        if (other.getPeerID() != 0) {
          setPeerID(other.getPeerID());
        }
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (other.getRoundtripTime() != 0) {
          setRoundtripTime(other.getRoundtripTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        foliv.FolivOuterClass.Foliv parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (foliv.FolivOuterClass.Foliv) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object userHash_ = "";
      /**
       * <code>string userHash = 1;</code>
       * @return The userHash.
       */
      public java.lang.String getUserHash() {
        java.lang.Object ref = userHash_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userHash_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userHash = 1;</code>
       * @return The bytes for userHash.
       */
      public com.google.protobuf.ByteString
          getUserHashBytes() {
        java.lang.Object ref = userHash_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userHash_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userHash = 1;</code>
       * @param value The userHash to set.
       * @return This builder for chaining.
       */
      public Builder setUserHash(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userHash = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserHash() {
        
        userHash_ = getDefaultInstance().getUserHash();
        onChanged();
        return this;
      }
      /**
       * <code>string userHash = 1;</code>
       * @param value The bytes for userHash to set.
       * @return This builder for chaining.
       */
      public Builder setUserHashBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userHash_ = value;
        onChanged();
        return this;
      }

      private int command_ = 0;
      /**
       * <code>.foliv.Command command = 2;</code>
       * @return The enum numeric value on the wire for command.
       */
      @java.lang.Override public int getCommandValue() {
        return command_;
      }
      /**
       * <code>.foliv.Command command = 2;</code>
       * @param value The enum numeric value on the wire for command to set.
       * @return This builder for chaining.
       */
      public Builder setCommandValue(int value) {
        
        command_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.foliv.Command command = 2;</code>
       * @return The command.
       */
      @java.lang.Override
      public foliv.FolivOuterClass.Command getCommand() {
        @SuppressWarnings("deprecation")
        foliv.FolivOuterClass.Command result = foliv.FolivOuterClass.Command.valueOf(command_);
        return result == null ? foliv.FolivOuterClass.Command.UNRECOGNIZED : result;
      }
      /**
       * <code>.foliv.Command command = 2;</code>
       * @param value The command to set.
       * @return This builder for chaining.
       */
      public Builder setCommand(foliv.FolivOuterClass.Command value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        command_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.foliv.Command command = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCommand() {
        
        command_ = 0;
        onChanged();
        return this;
      }

      private int addressType_ = 0;
      /**
       * <code>.foliv.AddressType addressType = 3;</code>
       * @return The enum numeric value on the wire for addressType.
       */
      @java.lang.Override public int getAddressTypeValue() {
        return addressType_;
      }
      /**
       * <code>.foliv.AddressType addressType = 3;</code>
       * @param value The enum numeric value on the wire for addressType to set.
       * @return This builder for chaining.
       */
      public Builder setAddressTypeValue(int value) {
        
        addressType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.foliv.AddressType addressType = 3;</code>
       * @return The addressType.
       */
      @java.lang.Override
      public foliv.FolivOuterClass.AddressType getAddressType() {
        @SuppressWarnings("deprecation")
        foliv.FolivOuterClass.AddressType result = foliv.FolivOuterClass.AddressType.valueOf(addressType_);
        return result == null ? foliv.FolivOuterClass.AddressType.UNRECOGNIZED : result;
      }
      /**
       * <code>.foliv.AddressType addressType = 3;</code>
       * @param value The addressType to set.
       * @return This builder for chaining.
       */
      public Builder setAddressType(foliv.FolivOuterClass.AddressType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        addressType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.foliv.AddressType addressType = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddressType() {
        
        addressType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString address_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes address = 4;</code>
       * @return The address.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getAddress() {
        return address_;
      }
      /**
       * <code>bytes address = 4;</code>
       * @param value The address to set.
       * @return This builder for chaining.
       */
      public Builder setAddress(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes address = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>uint32 port = 5;</code>
       * @return The port.
       */
      @java.lang.Override
      public int getPort() {
        return port_;
      }
      /**
       * <code>uint32 port = 5;</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 port = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object sourceName_ = "";
      /**
       * <code>string sourceName = 6;</code>
       * @return The sourceName.
       */
      public java.lang.String getSourceName() {
        java.lang.Object ref = sourceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sourceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sourceName = 6;</code>
       * @return The bytes for sourceName.
       */
      public com.google.protobuf.ByteString
          getSourceNameBytes() {
        java.lang.Object ref = sourceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sourceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sourceName = 6;</code>
       * @param value The sourceName to set.
       * @return This builder for chaining.
       */
      public Builder setSourceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sourceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sourceName = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearSourceName() {
        
        sourceName_ = getDefaultInstance().getSourceName();
        onChanged();
        return this;
      }
      /**
       * <code>string sourceName = 6;</code>
       * @param value The bytes for sourceName to set.
       * @return This builder for chaining.
       */
      public Builder setSourceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sourceName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object routerName_ = "";
      /**
       * <code>string routerName = 7;</code>
       * @return The routerName.
       */
      public java.lang.String getRouterName() {
        java.lang.Object ref = routerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          routerName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string routerName = 7;</code>
       * @return The bytes for routerName.
       */
      public com.google.protobuf.ByteString
          getRouterNameBytes() {
        java.lang.Object ref = routerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          routerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string routerName = 7;</code>
       * @param value The routerName to set.
       * @return This builder for chaining.
       */
      public Builder setRouterName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        routerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string routerName = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearRouterName() {
        
        routerName_ = getDefaultInstance().getRouterName();
        onChanged();
        return this;
      }
      /**
       * <code>string routerName = 7;</code>
       * @param value The bytes for routerName to set.
       * @return This builder for chaining.
       */
      public Builder setRouterNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        routerName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object processName_ = "";
      /**
       * <code>string processName = 8;</code>
       * @return The processName.
       */
      public java.lang.String getProcessName() {
        java.lang.Object ref = processName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          processName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string processName = 8;</code>
       * @return The bytes for processName.
       */
      public com.google.protobuf.ByteString
          getProcessNameBytes() {
        java.lang.Object ref = processName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          processName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string processName = 8;</code>
       * @param value The processName to set.
       * @return This builder for chaining.
       */
      public Builder setProcessName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        processName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string processName = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearProcessName() {
        
        processName_ = getDefaultInstance().getProcessName();
        onChanged();
        return this;
      }
      /**
       * <code>string processName = 8;</code>
       * @param value The bytes for processName to set.
       * @return This builder for chaining.
       */
      public Builder setProcessNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        processName_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> xForwardedFor_ = java.util.Collections.emptyList();
      private void ensureXForwardedForIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          xForwardedFor_ = new java.util.ArrayList<com.google.protobuf.ByteString>(xForwardedFor_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes xForwardedFor = 9;</code>
       * @return A list containing the xForwardedFor.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getXForwardedForList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(xForwardedFor_) : xForwardedFor_;
      }
      /**
       * <code>repeated bytes xForwardedFor = 9;</code>
       * @return The count of xForwardedFor.
       */
      public int getXForwardedForCount() {
        return xForwardedFor_.size();
      }
      /**
       * <code>repeated bytes xForwardedFor = 9;</code>
       * @param index The index of the element to return.
       * @return The xForwardedFor at the given index.
       */
      public com.google.protobuf.ByteString getXForwardedFor(int index) {
        return xForwardedFor_.get(index);
      }
      /**
       * <code>repeated bytes xForwardedFor = 9;</code>
       * @param index The index to set the value at.
       * @param value The xForwardedFor to set.
       * @return This builder for chaining.
       */
      public Builder setXForwardedFor(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureXForwardedForIsMutable();
        xForwardedFor_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes xForwardedFor = 9;</code>
       * @param value The xForwardedFor to add.
       * @return This builder for chaining.
       */
      public Builder addXForwardedFor(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureXForwardedForIsMutable();
        xForwardedFor_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes xForwardedFor = 9;</code>
       * @param values The xForwardedFor to add.
       * @return This builder for chaining.
       */
      public Builder addAllXForwardedFor(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureXForwardedForIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, xForwardedFor_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes xForwardedFor = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearXForwardedFor() {
        xForwardedFor_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private boolean isTouch_ ;
      /**
       * <code>bool isTouch = 10;</code>
       * @return The isTouch.
       */
      @java.lang.Override
      public boolean getIsTouch() {
        return isTouch_;
      }
      /**
       * <code>bool isTouch = 10;</code>
       * @param value The isTouch to set.
       * @return This builder for chaining.
       */
      public Builder setIsTouch(boolean value) {
        
        isTouch_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isTouch = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsTouch() {
        
        isTouch_ = false;
        onChanged();
        return this;
      }

      private int muxID_ ;
      /**
       * <code>uint32 muxID = 11;</code>
       * @return The muxID.
       */
      @java.lang.Override
      public int getMuxID() {
        return muxID_;
      }
      /**
       * <code>uint32 muxID = 11;</code>
       * @param value The muxID to set.
       * @return This builder for chaining.
       */
      public Builder setMuxID(int value) {
        
        muxID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 muxID = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearMuxID() {
        
        muxID_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object platform_ = "";
      /**
       * <code>string platform = 12;</code>
       * @return The platform.
       */
      public java.lang.String getPlatform() {
        java.lang.Object ref = platform_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          platform_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string platform = 12;</code>
       * @return The bytes for platform.
       */
      public com.google.protobuf.ByteString
          getPlatformBytes() {
        java.lang.Object ref = platform_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          platform_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string platform = 12;</code>
       * @param value The platform to set.
       * @return This builder for chaining.
       */
      public Builder setPlatform(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        platform_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string platform = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlatform() {
        
        platform_ = getDefaultInstance().getPlatform();
        onChanged();
        return this;
      }
      /**
       * <code>string platform = 12;</code>
       * @param value The bytes for platform to set.
       * @return This builder for chaining.
       */
      public Builder setPlatformBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        platform_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString requestID_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes requestID = 13;</code>
       * @return The requestID.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getRequestID() {
        return requestID_;
      }
      /**
       * <code>bytes requestID = 13;</code>
       * @param value The requestID to set.
       * @return This builder for chaining.
       */
      public Builder setRequestID(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes requestID = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestID() {
        
        requestID_ = getDefaultInstance().getRequestID();
        onChanged();
        return this;
      }

      private int routerLevel_ ;
      /**
       * <code>uint32 routerLevel = 14;</code>
       * @return The routerLevel.
       */
      @java.lang.Override
      public int getRouterLevel() {
        return routerLevel_;
      }
      /**
       * <code>uint32 routerLevel = 14;</code>
       * @param value The routerLevel to set.
       * @return This builder for chaining.
       */
      public Builder setRouterLevel(int value) {
        
        routerLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 routerLevel = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearRouterLevel() {
        
        routerLevel_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object userAgent_ = "";
      /**
       * <code>string userAgent = 15;</code>
       * @return The userAgent.
       */
      public java.lang.String getUserAgent() {
        java.lang.Object ref = userAgent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userAgent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userAgent = 15;</code>
       * @return The bytes for userAgent.
       */
      public com.google.protobuf.ByteString
          getUserAgentBytes() {
        java.lang.Object ref = userAgent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userAgent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userAgent = 15;</code>
       * @param value The userAgent to set.
       * @return This builder for chaining.
       */
      public Builder setUserAgent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userAgent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userAgent = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserAgent() {
        
        userAgent_ = getDefaultInstance().getUserAgent();
        onChanged();
        return this;
      }
      /**
       * <code>string userAgent = 15;</code>
       * @param value The bytes for userAgent to set.
       * @return This builder for chaining.
       */
      public Builder setUserAgentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userAgent_ = value;
        onChanged();
        return this;
      }

      private int requestHop_ ;
      /**
       * <code>uint32 requestHop = 16;</code>
       * @return The requestHop.
       */
      @java.lang.Override
      public int getRequestHop() {
        return requestHop_;
      }
      /**
       * <code>uint32 requestHop = 16;</code>
       * @param value The requestHop to set.
       * @return This builder for chaining.
       */
      public Builder setRequestHop(int value) {
        
        requestHop_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 requestHop = 16;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestHop() {
        
        requestHop_ = 0;
        onChanged();
        return this;
      }

      private int appID_ ;
      /**
       * <code>uint32 appID = 17;</code>
       * @return The appID.
       */
      @java.lang.Override
      public int getAppID() {
        return appID_;
      }
      /**
       * <code>uint32 appID = 17;</code>
       * @param value The appID to set.
       * @return This builder for chaining.
       */
      public Builder setAppID(int value) {
        
        appID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 appID = 17;</code>
       * @return This builder for chaining.
       */
      public Builder clearAppID() {
        
        appID_ = 0;
        onChanged();
        return this;
      }

      private int peerID_ ;
      /**
       * <code>uint32 peerID = 18;</code>
       * @return The peerID.
       */
      @java.lang.Override
      public int getPeerID() {
        return peerID_;
      }
      /**
       * <code>uint32 peerID = 18;</code>
       * @param value The peerID to set.
       * @return This builder for chaining.
       */
      public Builder setPeerID(int value) {
        
        peerID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 peerID = 18;</code>
       * @return This builder for chaining.
       */
      public Builder clearPeerID() {
        
        peerID_ = 0;
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <code>uint32 version = 19;</code>
       * @return The version.
       */
      @java.lang.Override
      public int getVersion() {
        return version_;
      }
      /**
       * <code>uint32 version = 19;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 version = 19;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private int roundtripTime_ ;
      /**
       * <code>uint32 roundtripTime = 20;</code>
       * @return The roundtripTime.
       */
      @java.lang.Override
      public int getRoundtripTime() {
        return roundtripTime_;
      }
      /**
       * <code>uint32 roundtripTime = 20;</code>
       * @param value The roundtripTime to set.
       * @return This builder for chaining.
       */
      public Builder setRoundtripTime(int value) {
        
        roundtripTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 roundtripTime = 20;</code>
       * @return This builder for chaining.
       */
      public Builder clearRoundtripTime() {
        
        roundtripTime_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:foliv.Foliv)
    }

    // @@protoc_insertion_point(class_scope:foliv.Foliv)
    private static final foliv.FolivOuterClass.Foliv DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new foliv.FolivOuterClass.Foliv();
    }

    public static foliv.FolivOuterClass.Foliv getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Foliv>
        PARSER = new com.google.protobuf.AbstractParser<Foliv>() {
      @java.lang.Override
      public Foliv parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Foliv(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Foliv> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Foliv> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public foliv.FolivOuterClass.Foliv getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_foliv_Foliv_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_foliv_Foliv_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013foliv.proto\022\005foliv\"\236\003\n\005Foliv\022\020\n\010userHa" +
      "sh\030\001 \001(\t\022\037\n\007command\030\002 \001(\0162\016.foliv.Comman" +
      "d\022\'\n\013addressType\030\003 \001(\0162\022.foliv.AddressTy" +
      "pe\022\017\n\007address\030\004 \001(\014\022\014\n\004port\030\005 \001(\r\022\022\n\nsou" +
      "rceName\030\006 \001(\t\022\022\n\nrouterName\030\007 \001(\t\022\023\n\013pro" +
      "cessName\030\010 \001(\t\022\025\n\rxForwardedFor\030\t \003(\014\022\017\n" +
      "\007isTouch\030\n \001(\010\022\r\n\005muxID\030\013 \001(\r\022\020\n\010platfor" +
      "m\030\014 \001(\t\022\021\n\trequestID\030\r \001(\014\022\023\n\013routerLeve" +
      "l\030\016 \001(\r\022\021\n\tuserAgent\030\017 \001(\t\022\022\n\nrequestHop" +
      "\030\020 \001(\r\022\r\n\005appID\030\021 \001(\r\022\016\n\006peerID\030\022 \001(\r\022\017\n" +
      "\007version\030\023 \001(\r\022\025\n\rroundtripTime\030\024 \001(\r*9\n" +
      "\007Command\022\t\n\005Empty\020\000\022\013\n\007Connect\020\001\022\r\n\tAsso" +
      "ciate\020\003\022\007\n\003Mux\020\177*B\n\013AddressType\022\017\n\013Inval" +
      "idType\020\000\022\010\n\004IPv4\020\001\022\016\n\nDomainName\020\003\022\010\n\004IP" +
      "v6\020\004B\tZ\007./folivb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_foliv_Foliv_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_foliv_Foliv_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_foliv_Foliv_descriptor,
        new java.lang.String[] { "UserHash", "Command", "AddressType", "Address", "Port", "SourceName", "RouterName", "ProcessName", "XForwardedFor", "IsTouch", "MuxID", "Platform", "RequestID", "RouterLevel", "UserAgent", "RequestHop", "AppID", "PeerID", "Version", "RoundtripTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
