# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: foliv.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("foliv.proto", :syntax => :proto3) do
    add_message "foliv.Foliv" do
      optional :userHash, :string, 1
      optional :command, :enum, 2, "foliv.Command"
      optional :addressType, :enum, 3, "foliv.AddressType"
      optional :address, :string, 4
      optional :port, :uint32, 5
      optional :sourceName, :string, 6
      optional :routerName, :string, 7
    end
    add_enum "foliv.Command" do
      value :Empty, 0
      value :Connect, 1
      value :Associate, 3
      value :Mux, 127
    end
    add_enum "foliv.AddressType" do
      value :InvalidType, 0
      value :IPv4, 1
      value :DomainName, 3
      value :IPv6, 4
    end
  end
end

module Foliv
  Foliv = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("foliv.Foliv").msgclass
  Command = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("foliv.Command").enummodule
  AddressType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("foliv.AddressType").enummodule
end
