<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: foliv.proto

namespace Foliv;

use UnexpectedValueException;

/**
 * Protobuf type <code>foliv.AddressType</code>
 */
class AddressType
{
    /**
     * Generated from protobuf enum <code>InvalidType = 0;</code>
     */
    const InvalidType = 0;
    /**
     * Generated from protobuf enum <code>IPv4 = 1;</code>
     */
    const IPv4 = 1;
    /**
     * Generated from protobuf enum <code>DomainName = 3;</code>
     */
    const DomainName = 3;
    /**
     * Generated from protobuf enum <code>IPv6 = 4;</code>
     */
    const IPv6 = 4;

    private static $valueToName = [
        self::InvalidType => 'InvalidType',
        self::IPv4 => 'IPv4',
        self::DomainName => 'DomainName',
        self::IPv6 => 'IPv6',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

