<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: foliv.proto

namespace Foliv;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>foliv.Foliv</code>
 */
class Foliv extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string userHash = 1;</code>
     */
    protected $userHash = '';
    /**
     * Generated from protobuf field <code>.foliv.Command command = 2;</code>
     */
    protected $command = 0;
    /**
     * Generated from protobuf field <code>.foliv.AddressType addressType = 3;</code>
     */
    protected $addressType = 0;
    /**
     * Generated from protobuf field <code>bytes address = 4;</code>
     */
    protected $address = '';
    /**
     * Generated from protobuf field <code>uint32 port = 5;</code>
     */
    protected $port = 0;
    /**
     * Generated from protobuf field <code>string sourceName = 6;</code>
     */
    protected $sourceName = '';
    /**
     * Generated from protobuf field <code>string routerName = 7;</code>
     */
    protected $routerName = '';
    /**
     * Generated from protobuf field <code>string processName = 8;</code>
     */
    protected $processName = '';
    /**
     * Generated from protobuf field <code>repeated bytes xForwardedFor = 9;</code>
     */
    private $xForwardedFor;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $userHash
     *     @type int $command
     *     @type int $addressType
     *     @type string $address
     *     @type int $port
     *     @type string $sourceName
     *     @type string $routerName
     *     @type string $processName
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $xForwardedFor
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Foliv::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string userHash = 1;</code>
     * @return string
     */
    public function getUserHash()
    {
        return $this->userHash;
    }

    /**
     * Generated from protobuf field <code>string userHash = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserHash($var)
    {
        GPBUtil::checkString($var, True);
        $this->userHash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.foliv.Command command = 2;</code>
     * @return int
     */
    public function getCommand()
    {
        return $this->command;
    }

    /**
     * Generated from protobuf field <code>.foliv.Command command = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCommand($var)
    {
        GPBUtil::checkEnum($var, \Foliv\Command::class);
        $this->command = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.foliv.AddressType addressType = 3;</code>
     * @return int
     */
    public function getAddressType()
    {
        return $this->addressType;
    }

    /**
     * Generated from protobuf field <code>.foliv.AddressType addressType = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setAddressType($var)
    {
        GPBUtil::checkEnum($var, \Foliv\AddressType::class);
        $this->addressType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes address = 4;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>bytes address = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, False);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 port = 5;</code>
     * @return int
     */
    public function getPort()
    {
        return $this->port;
    }

    /**
     * Generated from protobuf field <code>uint32 port = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setPort($var)
    {
        GPBUtil::checkUint32($var);
        $this->port = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sourceName = 6;</code>
     * @return string
     */
    public function getSourceName()
    {
        return $this->sourceName;
    }

    /**
     * Generated from protobuf field <code>string sourceName = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setSourceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->sourceName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string routerName = 7;</code>
     * @return string
     */
    public function getRouterName()
    {
        return $this->routerName;
    }

    /**
     * Generated from protobuf field <code>string routerName = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setRouterName($var)
    {
        GPBUtil::checkString($var, True);
        $this->routerName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string processName = 8;</code>
     * @return string
     */
    public function getProcessName()
    {
        return $this->processName;
    }

    /**
     * Generated from protobuf field <code>string processName = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setProcessName($var)
    {
        GPBUtil::checkString($var, True);
        $this->processName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes xForwardedFor = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getXForwardedFor()
    {
        return $this->xForwardedFor;
    }

    /**
     * Generated from protobuf field <code>repeated bytes xForwardedFor = 9;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setXForwardedFor($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->xForwardedFor = $arr;

        return $this;
    }

}

